import type { SapFieldDef } from "./types";

/**
 * Modules 6 & 7 — Billing & Invoices, Payments & Statement.
 * Source: docs/03-FUNCTIONAL-SPEC.md, Screens 6.1-6.2 and 7.1-7.2.
 *
 * Almost every row here is `R`: billing documents and FI open items are
 * written by SAP, never by the portal. The registry still earns its place —
 * the invoice and statement screens render lengths, labels and SAP origins
 * from it, and the one genuinely writable slice (a payment's allocations)
 * derives its Zod schema from the same rows rather than a hand-written one
 * (CLAUDE.md rule 3).
 */
export const billingMapping: readonly SapFieldDef[] = [
  // Screen 6.1 — View Invoices
  {
    portalField: "invoiceNumber",
    label: "Invoice No.",
    sapTable: "VBRK",
    sapField: "VBELN",
    sapType: "CHAR",
    length: 10,
    required: "R",
    notes: "VF03 display; the billing document number",
  },
  {
    portalField: "billingDate",
    label: "Invoice Date",
    sapTable: "VBRK",
    sapField: "FKDAT",
    sapType: "DATS",
    required: "R",
  },
  {
    portalField: "billingType",
    label: "Document Type",
    sapTable: "VBRK",
    sapField: "FKART",
    sapType: "CHAR",
    length: 4,
    required: "R",
    notes: "F2 invoice / G2 credit note / L2 debit note (Screen 6.2)",
  },
  {
    portalField: "reference",
    label: "Ref. SO/Delivery",
    sapTable: "VBRP",
    sapField: "VGBEL",
    sapType: "CHAR",
    length: 10,
    required: "R",
    notes: "Preceding document — the delivery, or the order when billed directly",
  },
  {
    portalField: "taxableAmount",
    label: "Taxable Amount",
    sapTable: "VBRP",
    sapField: "NETWR",
    sapType: "CURR",
    length: 15,
    required: "R",
    notes: "Ex-GST",
  },
  {
    portalField: "cgst",
    label: "CGST",
    sapTable: "KONV",
    sapField: "KBETR",
    sapType: "CURR",
    length: 15,
    required: "R",
    notes: "Condition JOCG — intra-state only",
  },
  {
    portalField: "sgst",
    label: "SGST",
    sapTable: "KONV",
    sapField: "KBETR",
    sapType: "CURR",
    length: 15,
    required: "R",
    notes: "Condition JOSG — intra-state only",
  },
  {
    portalField: "igst",
    label: "IGST",
    sapTable: "KONV",
    sapField: "KBETR",
    sapType: "CURR",
    length: 15,
    required: "R",
    notes: "Condition JOIG — inter-state only",
  },
  {
    portalField: "grossAmount",
    label: "Total",
    sapTable: "VBRK",
    sapField: "NETWR",
    sapType: "CURR",
    length: 15,
    required: "R",
    notes: "Gross, incl. GST",
  },
  {
    portalField: "irn",
    label: "IRN",
    sapTable: "J_1IEXCHDR",
    sapField: "J_1I_IRN",
    sapType: "CHAR",
    length: 64,
    required: "R",
    notes: "Mandatory above the e-invoicing turnover threshold; portal displays only",
  },
  {
    portalField: "dueDate",
    label: "Due Date",
    sapTable: "BSID",
    sapField: "ZFBDT",
    sapType: "DATS",
    required: "R",
    notes: "Baseline date + payment terms",
  },

  // Screen 6.2 — Credit / Debit Notes
  {
    portalField: "reasonCode",
    label: "Reason Code",
    sapTable: "VBRP",
    sapField: "MGAGR",
    sapType: "CHAR",
    length: 3,
    required: "R",
    notes: "Order reason on the credit/debit memo request",
  },

  // Screen 7.1 — Account Statement
  {
    portalField: "documentNumber",
    label: "Document No.",
    sapTable: "BSID",
    sapField: "BELNR",
    sapType: "CHAR",
    length: 10,
    required: "R",
    notes: "FI document; BSID while open, BSAD once cleared",
  },
  {
    portalField: "documentType",
    label: "Doc Type",
    sapTable: "BKPF",
    sapField: "BLART",
    sapType: "CHAR",
    length: 2,
    required: "R",
    notes: "RV invoice / DZ payment / G2 credit note",
  },
  {
    portalField: "postingDate",
    label: "Posting Date",
    sapTable: "BKPF",
    sapField: "BUDAT",
    sapType: "DATS",
    required: "R",
  },
  {
    portalField: "amount",
    label: "Amount",
    sapTable: "BSEG",
    sapField: "WRBTR",
    sapType: "CURR",
    length: 15,
    required: "R",
    notes: "Posting key 01 debits the customer, 15 credits it",
  },
  {
    portalField: "openAmount",
    label: "Outstanding",
    sapTable: "BSID",
    sapField: "DMBTR",
    sapType: "CURR",
    length: 15,
    required: "R",
  },
  {
    portalField: "clearingDocument",
    label: "Clearing Doc.",
    sapTable: "BSEG",
    sapField: "AUGBL",
    sapType: "CHAR",
    length: 10,
    required: "R",
    notes: "Set by the clearing posting; empty while the item is open",
  },

  // Screen 7.2 — Make Payment (the module's only writable fields)
  {
    portalField: "payDocumentNumber",
    label: "Invoice",
    sapTable: "BSID",
    sapField: "BELNR",
    sapType: "CHAR",
    length: 10,
    required: "M",
    notes: "An open item selected for payment",
  },
  {
    portalField: "payAmount",
    label: "Amount to Pay",
    sapTable: "BSEG",
    sapField: "WRBTR",
    sapType: "CURR",
    length: 15,
    required: "M",
    notes: "Full or partial; a partial payment leaves a residual open item",
  },
  {
    portalField: "paymentMode",
    label: "Payment Mode",
    sapTable: "BSEG",
    sapField: "ZLSCH",
    sapType: "SELECT",
    length: 1,
    required: "M",
    notes: "UPI / NEFT / Card / NetBanking — the gateway's method, mapped to ZLSCH on posting",
  },
  {
    portalField: "gatewayReference",
    label: "Payment Reference",
    sapTable: "BSEG",
    sapField: "KIDNO",
    sapType: "CHAR",
    length: 30,
    required: "R",
    notes: "Gateway reference, auto-filled on posting; the portal's idempotency key",
  },
];
