import type { SapFieldDef } from "./types";

/**
 * Module 1 — Customer Onboarding.
 * Source: docs/03-FUNCTIONAL-SPEC.md, Screens 1.1-1.4.
 * ECC field names are the default; per-tenant overrides go through the
 * field mapping engine (docs/02-TRD-ARCHITECTURE.md §4.2), not here.
 */
export const onboardingMapping: readonly SapFieldDef[] = [
  // Screen 1.1 — Company Information
  {
    portalField: "legalEntityName",
    label: "Legal Entity Name",
    sapTable: "KNA1",
    sapField: "NAME1",
    sapType: "CHAR",
    length: 35,
    required: "M",
    notes: "As per registration certificate",
  },
  {
    portalField: "tradeName",
    label: "Trade/Brand Name",
    sapTable: "KNA1",
    sapField: "NAME2",
    sapType: "CHAR",
    length: 35,
    required: "O",
  },
  {
    portalField: "customerType",
    label: "Customer Type",
    sapTable: "KNA1",
    sapField: "KTOKD",
    sapType: "CHAR",
    length: 4,
    required: "M",
    notes: "Account group: Retailer/Distributor/Direct/Export — controls field selection",
  },
  {
    portalField: "street",
    label: "Street/Area",
    sapTable: "KNA1",
    sapField: "STRAS",
    sapType: "CHAR",
    length: 35,
    required: "M",
  },
  {
    portalField: "city",
    label: "City",
    sapTable: "KNA1",
    sapField: "ORT01",
    sapType: "CHAR",
    length: 35,
    required: "M",
  },
  {
    portalField: "state",
    label: "State",
    sapTable: "KNA1",
    sapField: "REGIO",
    sapType: "CHAR",
    length: 3,
    required: "M",
    notes: "T005S; drives GST Place of Supply",
  },
  {
    portalField: "pinCode",
    label: "PIN Code",
    sapTable: "KNA1",
    sapField: "PSTLZ",
    sapType: "CHAR",
    length: 10,
    required: "M",
    notes: "6-digit validation",
  },
  {
    portalField: "country",
    label: "Country",
    sapTable: "KNA1",
    sapField: "LAND1",
    sapType: "CHAR",
    length: 3,
    required: "M",
    notes: "Default IN",
  },
  {
    portalField: "contactPerson",
    label: "Contact Person",
    sapTable: "KNA1",
    sapField: "ANSPK",
    sapType: "CHAR",
    length: 30,
    required: "M",
  },
  {
    portalField: "email",
    label: "Email",
    sapTable: "ADR6",
    sapField: "SMTP_ADDR",
    sapType: "CHAR",
    length: 241,
    required: "M",
    notes: "Portal login ID; comm type INT",
  },
  {
    portalField: "phone",
    label: "Phone",
    sapTable: "KNA1",
    sapField: "TELF1",
    sapType: "CHAR",
    length: 16,
    required: "M",
    notes: "10-15 digits",
  },

  // Screen 1.2 — Tax & Regulatory
  {
    portalField: "pan",
    label: "PAN",
    sapTable: "KNA1",
    sapField: "STCD3",
    sapType: "CHAR",
    length: 10,
    required: "M",
    notes: "Format AAAAA9999A",
  },
  {
    portalField: "gstin",
    label: "GSTIN",
    sapTable: "KNA1",
    sapField: "STCD2",
    sapType: "CHAR",
    length: 15,
    required: "M",
    notes: "Real-time GSTN API verification; must contain PAN; state code must match REGIO",
  },
  {
    portalField: "gstRegistrationType",
    label: "GST Registration Type",
    sapTable: "J_1IMOCUST",
    sapField: "J_1IGSTIN_REGTP",
    sapType: "CHAR",
    length: 2,
    required: "M",
    notes: "01 Regular / 02 Composition / 03 Unregistered / 04 SEZ",
  },
  {
    portalField: "cin",
    label: "CIN",
    sapTable: "KNA1",
    sapField: "STCD1",
    sapType: "CHAR",
    length: 21,
    required: "O",
    notes: "Pvt/Public Ltd",
  },
  {
    portalField: "tan",
    label: "TAN",
    sapTable: "KNA1",
    sapField: "STCD4",
    sapType: "CHAR",
    length: 10,
    required: "O",
    notes: "TCS applicability",
  },
  {
    portalField: "msmeUdyamNo",
    label: "MSME/Udyam No.",
    sapTable: "KNA1",
    sapField: "STCD5",
    sapType: "CHAR",
    length: 20,
    required: "O",
    notes: "Buyer MSME obligations",
  },

  // Screen 1.3 — Credit & Commercial Terms
  {
    portalField: "requestedCreditLimit",
    label: "Requested Credit Limit ₹",
    sapTable: "KNKK",
    sapField: "KLIMK",
    sapType: "CURR",
    length: 15,
    required: "M",
    notes: "Subject to approval (FD32)",
  },
  {
    portalField: "paymentTermsRequested",
    label: "Payment Terms Requested",
    sapTable: "KNVV",
    sapField: "ZTERM",
    sapType: "CHAR",
    length: 4,
    required: "O",
    notes: "T052",
  },
  {
    portalField: "preferredSalesOffice",
    label: "Preferred Sales Office",
    sapTable: "KNVV",
    sapField: "VKBUR",
    sapType: "CHAR",
    length: 4,
    required: "O",
  },
  {
    portalField: "accountHolderName",
    label: "Account Holder Name",
    sapTable: "BNKA",
    sapField: "KOINH",
    sapType: "CHAR",
    length: 60,
    required: "O",
    notes: "Refunds",
  },
  {
    portalField: "bankAccountNo",
    label: "Bank Account No.",
    sapTable: "KNBK",
    sapField: "BANKN",
    sapType: "CHAR",
    length: 18,
    required: "O",
  },
  {
    portalField: "ifsc",
    label: "IFSC",
    sapTable: "KNBK",
    sapField: "BANKL",
    sapType: "CHAR",
    length: 11,
    required: "O",
  },

  // Screen 1.4 — Documents & Approval
  {
    portalField: "panCardCopy",
    label: "PAN Card Copy",
    sapTable: "GOS",
    sapField: "ATTACHMENT",
    sapType: "FILE",
    required: "M",
    notes: "Stored in portal object storage; attached to SAP customer via GOS on creation",
  },
  {
    portalField: "gstCertificate",
    label: "GST Certificate",
    sapTable: "GOS",
    sapField: "ATTACHMENT",
    sapType: "FILE",
    required: "M",
    notes: "Must match GSTIN",
  },
  {
    portalField: "incorporationCert",
    label: "Incorporation Certificate",
    sapTable: "GOS",
    sapField: "ATTACHMENT",
    sapType: "FILE",
    required: "O",
  },
  {
    portalField: "salesOrg",
    label: "Sales Org",
    sapTable: "KNVV",
    sapField: "VKORG",
    sapType: "CHAR",
    length: 4,
    required: "M",
    notes: "Internal approval field",
  },
  {
    portalField: "distributionChannel",
    label: "Distribution Channel",
    sapTable: "KNVV",
    sapField: "VTWEG",
    sapType: "CHAR",
    length: 2,
    required: "M",
    notes: "Determines pricing procedure; internal approval field",
  },
  {
    portalField: "creditApprovalStatus",
    label: "Credit Approval Status",
    sapTable: "KNKK",
    sapField: "CTLPC",
    sapType: "SELECT",
    required: "O",
    notes: "Internal approval field",
  },

  // Read-only, populated on approval (BAPI_CUSTOMER_CREATEFROMDATA1 result)
  {
    portalField: "sapCustomerCode",
    label: "SAP Customer Code",
    sapTable: "KNA1",
    sapField: "KUNNR",
    sapType: "CHAR",
    length: 10,
    required: "R",
    notes: "Synced back after Approve & Create in SAP",
  },
] as const;
