import type { SapFieldDef } from "./types";

/**
 * Module 4 — Sales Order Management.
 * Source: docs/03-FUNCTIONAL-SPEC.md, Screens 4.1-4.2.
 */
export const orderMapping: readonly SapFieldDef[] = [
  // Screen 4.1 — Create Order: Header
  {
    portalField: "customerPoRef",
    label: "Customer PO Ref",
    sapTable: "VBKD",
    sapField: "BSTNK",
    sapType: "CHAR",
    length: 20,
    required: "O",
    notes: "Printed on confirmation; also used as portal idempotency key",
  },
  {
    portalField: "requestedDeliveryDate",
    label: "Requested Delivery Date",
    sapTable: "VBAK",
    sapField: "VDATU",
    sapType: "DATS",
    required: "M",
  },
  {
    portalField: "shipTo",
    label: "Ship-to",
    sapTable: "VBPA",
    sapField: "KUNNR",
    sapType: "CHAR",
    length: 10,
    required: "M",
    notes: "Partner function SH; selected from saved addresses",
  },

  // Screen 4.1 — Create Order: Line items
  {
    portalField: "material",
    label: "Material",
    sapTable: "VBAP",
    sapField: "MATNR",
    sapType: "CHAR",
    length: 18,
    required: "M",
  },
  {
    portalField: "quantity",
    label: "Quantity",
    sapTable: "VBAP",
    sapField: "KWMENG",
    sapType: "QUAN",
    length: 13,
    required: "M",
  },
  {
    portalField: "uom",
    label: "UoM",
    sapTable: "VBAP",
    sapField: "VRKME",
    sapType: "UNIT",
    length: 3,
    required: "M",
  },
  {
    portalField: "price",
    label: "Price",
    sapTable: "VBAP",
    sapField: "NETPR",
    sapType: "CURR",
    length: 11,
    required: "C",
    notes:
      "Read-only, pre-filled when the order originates from an accepted quotation; editable/mandatory on a direct order",
  },
  {
    portalField: "plant",
    label: "Plant",
    sapTable: "VBAP",
    sapField: "WERKS",
    sapType: "CHAR",
    length: 4,
    required: "R",
    notes: "Auto-derived",
  },

  // Screen 4.1 — Create Order: Terms
  {
    portalField: "paymentTerms",
    label: "Payment Terms",
    sapTable: "VBKD",
    sapField: "ZTERM",
    sapType: "CHAR",
    length: 4,
    required: "O",
    notes: "Defaults from KNVV-ZTERM",
  },
  {
    portalField: "incoterms",
    label: "Incoterms",
    sapTable: "VBKD",
    sapField: "INCO1",
    sapType: "CHAR",
    length: 4,
    required: "O",
  },
  {
    portalField: "deliveryPriority",
    label: "Delivery Priority",
    sapTable: "VBAK",
    sapField: "LPRIO",
    sapType: "CHAR",
    length: 2,
    required: "O",
  },

  // Screen 4.2 — Order Status & Confirmation (read-only)
  {
    portalField: "soNumber",
    label: "SO Number",
    sapTable: "VBAK",
    sapField: "VBELN",
    sapType: "CHAR",
    length: 10,
    required: "R",
  },
  {
    portalField: "orderStatus",
    label: "Order Status",
    sapTable: "VBUK",
    sapField: "GBSTK",
    sapType: "STATUS",
    length: 1,
    required: "R",
    notes: "A Open / B Partial / C Complete",
  },
  {
    portalField: "confirmedQty",
    label: "Confirmed Qty",
    sapTable: "VBEP",
    sapField: "BMENG",
    sapType: "QUAN",
    length: 13,
    required: "R",
    notes: "Per schedule line",
  },
  {
    portalField: "confirmedDate",
    label: "Confirmed Date",
    sapTable: "VBEP",
    sapField: "EDATU",
    sapType: "DATS",
    required: "R",
  },
  {
    portalField: "creditStatus",
    label: "Credit Status",
    sapTable: "VBUK",
    sapField: "CMGST",
    sapType: "STATUS",
    length: 1,
    required: "R",
    notes: "A not checked / B blocked / C released",
  },
  {
    portalField: "orderConfirmationPdf",
    label: "Order Confirmation PDF",
    sapTable: "NAST",
    sapField: "OBJKY",
    sapType: "FILE",
    required: "R",
    notes: "Output type BA00",
  },
] as const;
